version: "3.8"

services:
  backend:
    build: ./backend
    container_name: hrms_backend
    command: sh -c "python patch_djongo.py && python manage.py migrate --noinput && gunicorn hrms_core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db:27017/hrms_db
      - DJANGO_SETTINGS_MODULE=hrms_core.settings

  frontend:
    build: ./frontend
    container_name: hrms_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mongo:4.4
    container_name: hrms_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
